import { injectProvenance } from "../core/provenance.js";
import { sha256 } from "../core/paths.js";
import type { Stack, RepoMap } from "../scanners/types.js";

export interface RenderStackArgs {
  stack: Stack;
  repoMap: RepoMap;
  projectName: string;
  generatorVersion: string;
  now: string;
  sourceSha: string;
}

/**
 * Pure markdown renderer for `agent/stack.md`. Includes a frontmatter block
 * so the file slots into the MemorySet alongside authored files, and a
 * provenance HTML-comment header (same shape as adapter-generated files).
 */
export function renderStackMd(args: RenderStackArgs): string {
  const { stack, repoMap, projectName, generatorVersion, now, sourceSha } = args;

  const frontmatter = [
    "---",
    "name: stack",
    `description: Auto-detected tech stack for ${projectName}.`,
    "source: generated",
    "priority: 30",
    'applies_to: ["*"]',
    "tags: [stack, dependencies]",
    "---",
    "",
  ].join("\n");

  const langHistogram = repoMap.summary.languages
    .slice(0, 10)
    .map((l) => `- **${l.language}**: ${l.lines} lines across ${l.files} file${l.files === 1 ? "" : "s"}`)
    .join("\n");

  const body = [
    "# Stack",
    "",
    `> Auto-generated by \`agentctx scan\`. Re-run after dependency or stack changes.`,
    "",
    "## Languages",
    "",
    bulletList(stack.languages),
    "",
    "## Runtimes",
    "",
    bulletList(stack.runtimes),
    "",
    "## Package managers",
    "",
    bulletList(stack.packageManagers),
    "",
    "## Frameworks",
    "",
    bulletList(stack.frameworks),
    "",
    "## CI",
    "",
    bulletList(stack.ci),
    "",
    "## Code shape",
    "",
    `- **Total files**: ${repoMap.summary.totalFiles}`,
    `- **Total lines**: ${repoMap.summary.totalLines}`,
    "",
    langHistogram || "_No recognized source languages found._",
    "",
  ].join("\n");

  const withFrontmatter = frontmatter + body;
  return injectProvenance(withFrontmatter, {
    sourceSha,
    generator: `stack-generator@${generatorVersion}`,
    generatedAt: now,
  });
}

function bulletList(items: string[]): string {
  if (items.length === 0) return "_none detected_";
  return items.map((i) => `- ${i}`).join("\n");
}

/** sha256 of the generator body (without provenance) for cache/checksum use. */
export function stackChecksum(body: string): string {
  return sha256(body);
}
