import type { Adapter, GeneratedFile, RenderContext } from "./base.js";
import type { MemorySet } from "../core/memory.js";
import { renderFile, buildStandardBody } from "./_render.js";

const NAME = "agents-md";
const VERSION = "0.1.0";

export const agentsMdAdapter: Adapter = {
  name: NAME,
  version: VERSION,
  outputPaths: ["AGENTS.md"],

  async render(memory: MemorySet, ctx: RenderContext): Promise<GeneratedFile[]> {
    const file = renderFile({
      adapterName: NAME,
      adapterVersion: VERSION,
      outputPath: "AGENTS.md",
      memory,
      ctx,
      buildBody: (sections, truncated) =>
        buildStandardBody(
          sections,
          truncated,
          `# ${ctx.projectName} — Agent Context\n\nThis file is auto-generated by agentsync. Edit files in \`agent/\` and run \`agentsync sync\`.`,
        ),
    });
    return [file];
  },
};
