import type { Adapter, GeneratedFile, RenderContext } from "./base.js";
import type { MemorySet } from "../core/memory.js";
import { renderFile, buildStandardBody } from "./_render.js";

const NAME = "cline";
const VERSION = "0.1.0";

export const clineAdapter: Adapter = {
  name: NAME,
  version: VERSION,
  outputPaths: [".clinerules"],

  async render(memory: MemorySet, ctx: RenderContext): Promise<GeneratedFile[]> {
    const file = renderFile({
      adapterName: NAME,
      adapterVersion: VERSION,
      outputPath: ".clinerules",
      memory,
      ctx,
      buildBody: (sections, truncated) =>
        buildStandardBody(
          sections,
          truncated,
          `# ${ctx.projectName} — Cline Rules\n\nAuto-generated by agentctx. Edit files in \`agent/\` and run \`agentctx sync\`.`,
        ),
    });
    return [file];
  },
};
