import type { Adapter, GeneratedFile, RenderContext } from "./base.js";
import type { MemorySet } from "../core/memory.js";
import { applyTokenBudget, computeSourceSha } from "./base.js";
import { injectProvenance } from "../core/provenance.js";
import { sha256 } from "../core/paths.js";

const NAME = "cursor";
const VERSION = "0.1.0";

function buildCursorRules(
  sections: Array<{ path: string; body: string }>,
  truncated: boolean,
  projectName: string,
): string {
  const parts = [
    `# ${projectName} — Cursor Rules`,
    "",
    "Auto-generated by agentsync. Edit files in `agent/` and run `agentsync sync`.",
    "",
  ];
  for (const s of sections) {
    parts.push(s.body.trim());
    parts.push("");
  }
  if (truncated) {
    parts.push("---");
    parts.push("*Some sections were omitted due to token budget limits.*");
    parts.push("");
  }
  return parts.join("\n");
}

function buildMdcFile(
  filePath: string,
  body: string,
  projectName: string,
): string {
  const name = filePath.replace(/^agent\//, "").replace(/\.md$/, "");
  return `---\ndescription: ${name} rules for ${projectName}\nglobs:\nalwaysApply: true\n---\n\n${body.trim()}\n`;
}

export const cursorAdapter: Adapter = {
  name: NAME,
  version: VERSION,
  outputPaths: [".cursorrules", ".cursor/rules/agentsync.mdc"],

  async render(memory: MemorySet, ctx: RenderContext): Promise<GeneratedFile[]> {
    const sourceSha = computeSourceSha(memory);
    const { sections, truncated } = applyTokenBudget(memory, ctx, NAME);
    const provenanceFields = {
      sourceSha,
      generator: `${NAME}-adapter@${VERSION}`,
      generatedAt: ctx.now,
    };

    // .cursorrules — flat concatenation
    const rulesBody = buildCursorRules(sections, truncated, ctx.projectName);
    const rulesWithProvenance = injectProvenance(rulesBody, provenanceFields);
    const rulesFile: GeneratedFile = {
      path: ".cursorrules",
      contents: rulesWithProvenance,
      checksum: sha256(rulesBody),
      sourceSha,
    };

    // .cursor/rules/agentsync.mdc — MDC format
    const mdcContent = sections
      .map((s) => buildMdcFile(s.path, s.body, ctx.projectName))
      .join("\n---\n\n");
    const mdcBody = mdcContent || `# ${ctx.projectName}\n\nNo agent context found.\n`;
    const mdcWithProvenance = injectProvenance(mdcBody, provenanceFields);
    const mdcFile: GeneratedFile = {
      path: ".cursor/rules/agentsync.mdc",
      contents: mdcWithProvenance,
      checksum: sha256(mdcBody),
      sourceSha,
    };

    return [rulesFile, mdcFile];
  },
};
